#addon lists are prebuilt plugin lists to automate mass plugin registration

[metadata]
description=This registry list includes the addons distributed with Neoloader
version=1.0.0
owner=Neoloader|7.0.0
type=ini
created=2025-11-10

[modlist]
name=Neoloader bundled addons
prepend_local_path=YES
1=neomgr/neomgr.lua
2=neonotif/neonotif.lua
3=Vendetta Online Standard Interface/vosi.lua
#4=VoidIF/voidif.lua
#Developer only, added by setup process
